import type {Chrome, Lang} from './types';

/**
 * UI chrome, one entry per language. Fields the source never authored in a
 * language are simply absent — the screens render what exists rather than
 * showing an untranslated English string.
 */
export const CHROME: Record<Lang, Chrome> = {
  en: {
    documentTitle: 'Debugging AI-Generated Loops',
    unitTag: 'Iterating with AI',
    eyebrow: 'Loop Verification Checklist',
    introTitle: 'Debugging AI-Generated Loops',
    introSub: 'A practice simulation to help you guide students through checking AI-generated loop code before using it in class.',
    heroImgAlt: 'Ms. Rivera, the teacher, standing in a classroom',
    scenarioCard: {
      label: 'Scenario',
      header: 'Your Classroom — Right Now',
      studentLabel: 'Alex, one of your students',
      quote: 'I used AI to write my loop and something is off, but I cannot figure out what is wrong.',
      body: 'You just finished teaching loops. Alex raises his hand. He used AI to generate code that almost works — it runs, but the output is not right. Sound familiar? Run through the Loop Verification Checklist alongside Alex to find the bug, the same way you would in class.',
      imgAlt: 'Alex, a student, looking frustrated at his laptop',
    },
    missionHeading: 'Your Mission',
    missionText: "Run each check on Alex's loop. Answer Passes or Has an Issue for each one. The bug is hiding somewhere — your job is to find it and understand exactly why it matters before your students hit the same wall.",
    missionSteps: ['First Value Test', 'Last Value Test', 'Edge Test', 'Extra Iteration', 'Missing Iteration', 'Match Check'],
    startBtn: 'Start the Loop Verification Checklist →',
    startNote: '6 checks · approx. 5 minutes',
    progressOf: 'Check {n} of 6',
    teacherName: 'Ms. Rivera',
    studentName: 'Alex',
    teacherImgAlt: 'Ms. Rivera, the teacher',
    studentImgAlt: 'Alex, the student',
    btnPasses: '✓ Passes',
    btnIssue: '✗ Has an Issue',
    btnNext: 'Next Check →',
    btnResults: 'See Results →',
    bugTagLabel: 'BUG',
    consoleLabel: '▸ Console',
    consoleInitial: '// Run the checks to reveal the output',
    youSaidPasses: 'You answered: Passes',
    youSaidIssue: 'You answered: Has an Issue',
    verdictCorrect: 'You answered correctly',
    verdictIncorrect: 'Incorrect answer',
    scoreLabel: 'Checks passed',
    summaryEyebrow: 'Simulation Complete',
    summaryTitle: 'Debugging Complete: Bug Found',
    summarySub: "You ran all 6 checks on Alex's AI-generated loop and identified the off-by-one error. Here is what you found.",
    summaryImgAlt: 'Ms. Rivera, the teacher',
    recapTitle: 'All 6 Checks',
    issueLabel: 'Issue found',
    passLabel: 'Passed',
    takeaway: {
      name: 'Ms. Rivera',
      quote: 'Great detective work. The code looked right at first, but checks 1, 4, and 6 revealed the truth. This is exactly why we run the checklist before trusting AI output. Your students will hit this same wall.',
    },
    classroom: {
      label: 'Classroom Connection',
      text: 'When students say they are stuck, they have usually skipped Check 1 or Check 6 and have not verified where the loop starts, or compared the output to what was actually asked for. The Loop Verification Checklist gives you a shared language to redirect them without giving away the answer.',
    },
    btnRestart: 'Run the Checklist Again',
    restartNote: 'Iterating with AI · Debugging AI-Generated Loops',
    fallbackNote: 'This scenario has not been written in English yet, so the English off-by-one scenario is shown instead.',
  },
  es: {
    documentTitle: 'Cómo Probar Código de Loops Generado por IA',
    unitTag: 'Unidad 4 · Loops e IA',
    introTitle: 'Cómo Probar Código de Loops Generado por IA',
    introSub: 'Una rutina reutilizable de 6 pasos para evaluar loops antes de confiar en ellos en tus proyectos del aula.',
    introTeacherLine: 'Alex me acaba de mostrar un código de loop que generó la IA. Se ve correcto — ¿pero realmente funciona? Vamos a descubrirlo juntos.',
    missionHeading: 'Tu Misión',
    missionText: 'Ejecuta las 6 verificaciones en el loop de Alex generado por IA. Responde Sí o No en cada prueba. Descubre si el código es seguro de usar — o si hay un error oculto.',
    startBtn: 'Comenzar a Depurar con Alex →',
    progressOf: 'Verificación {n} de 6',
    teacherName: 'Sra. Rivera',
    studentName: 'Alex',
    teacherImgAlt: 'Sra. Rivera, la maestra',
    studentImgAlt: 'Alex, el estudiante',
    btnPasses: '✓ Sí, pasa la prueba',
    btnIssue: '✗ No, hay un problema',
    btnNext: 'Siguiente Verificación →',
    btnResults: 'Ver Resultados →',
    bugTagLabel: 'ERROR',
    consoleLabel: '▸ Console',
    consoleInitial: '// Responde las verificaciones para ver el resultado',
    youSaidPasses: 'Respondiste: Sí',
    youSaidIssue: 'Respondiste: No',
    verdictCorrect: 'Respondiste correctamente',
    verdictIncorrect: 'Respuesta incorrecta',
    scoreLabel: 'Verificaciones superadas',
    summaryTitle: '🔍 ¡Depuración Completa!',
    summarySub: 'Esto es lo que encontraste en el loop de Alex generado por IA.',
    btnRestart: 'Intentar de Nuevo',
    fallbackNote: 'Esta actividad no existe en español para ese escenario; se muestra el escenario de rango incorrecto.',
  },
};
