import type {Scenario, ScenarioId} from './types';

/**
 * The bug under test. Each scenario exists in exactly one language: the
 * English sources teach the off-by-one loop, the Spanish sources teach a
 * different loop with a shifted range. Neither was ever translated, so
 * `lang` records which language a scenario's copy can be shown in.
 */
export const SCENARIOS: Record<ScenarioId, Scenario> = {
  'off-by-one': {
    lang: 'en',
    code: {
      comment: '// Alex asked AI: Print numbers 1 to 5',
      loop: 'for (let i = 0; i <= 5; i++) {',
      body: '  console.log(i);',
      close: '}',
      expected: '// Expected: 1, 2, 3, 4, 5',
      actualUnknown: '// Actual:   ???',
      actualRevealed: '// Actual:   0, 1, 2, 3, 4, 5  (6 values)',
    },
    consoleOutput: ['0', '1', '2', '3', '4', '5'],
    consoleWarning: '// 6 values — expected 5',
    revealAt: 3,
    bugCallout: {
      label: 'The Bug',
      title: 'Off-by-one error: a classic AI mistake',
      aiLabel: '// What the AI wrote',
      aiCode: 'for (let i = 0; i <= 5; i++) {',
      aiComment: '// prints 0,1,2,3,4,5 (6 values)',
      fixLabel: '// What it should be',
      fixCode: 'for (let i = 1; i <= 5; i++) {',
      fixComment: '// prints 1,2,3,4,5 (5 values)',
      explanation: 'The AI used i = 0 and i <= 5, a classic off-by-one error. Starting at 0 instead of 1 adds an extra iteration, printing 6 values instead of 5. Change i = 0 to i = 1 to fix it. AI tools make this mistake often because they default to zero-indexed logic, which is exactly why the Loop Verification Checklist exists.',
    },
    checks: [
      {
        title: 'First Value Test',
        teacherLine: 'Look closely at where i starts. Alex asked for numbers beginning at 1. What does the code actually say?',
        studentLine: 'The AI said starting at 0 is fine because it adjusts with the condition. Is that right?',
        question: 'Does the loop start where Alex expected? He asked for numbers starting at 1. Does i = 0 match that?',
        correctIsIssue: true,
        correctLabel: 'Good instinct — there is an issue',
        correctBody: 'i starts at 0, but Alex asked for numbers starting at 1. The loop will include 0 in its output. That is the first sign of a bug. Keep going to see the full picture.',
        wrongLabel: 'Check again — the logic does not pass here',
        wrongBody: 'Look at the starting value: i = 0. Alex asked for numbers starting at 1. The loop starts one step too early. This is already off before it runs a single time.',
        reactionCorrect: 'Oh! So it starts at 0, not 1? I did not even notice that. So it is already wrong from the very first number?',
        reactionIncorrect: 'Wait, i starts at 0? I thought 0 and 1 were basically the same thing in loops. Are they not?',
        highlight: 'loop',
        recapNote: 'Loop starts at i = 0, but Alex asked for values starting at 1. Already off before a single iteration runs.',
      },
      {
        title: 'Last Value Test',
        teacherLine: 'The last value looks okay on its own. But remember, we found a problem in check 1. Could that affect the total count?',
        studentLine: 'So i <= 5 is okay... but something still feels off.',
        question: 'Does the loop stop at the right place? Alex wanted to end at 5. Does i <= 5 stop correctly?',
        correctIsIssue: false,
        correctLabel: 'Good instinct — this one holds',
        correctBody: 'i <= 5 does stop when i reaches 5. The upper boundary is correct on its own. But combined with what we found in check 1, the full picture is still off.',
        wrongLabel: 'Check again — the logic does pass here',
        wrongBody: 'i <= 5 does include 5 and stops correctly after. The last value condition is fine on its own. The issue is elsewhere in the loop.',
        reactionCorrect: 'So the stopping point is fine... then the problem must be somewhere else.',
        reactionIncorrect: 'Oh, so i <= 5 actually works correctly? Then where is the real problem?',
        highlight: 'loop',
        recapNote: 'i <= 5 correctly stops after reaching 5. The upper boundary holds on its own.',
      },
      {
        title: 'Edge Test',
        teacherLine: 'Edge cases are where loops often break. Check whether the loop handles the boundary at exactly 5 correctly.',
        studentLine: 'Okay so the edges are fine... then why do I still have a feeling something is wrong?',
        question: 'What happens at the boundary? When i equals exactly 5, does the loop include it and then stop cleanly?',
        correctIsIssue: false,
        correctLabel: 'Good instinct — the edge is clean',
        correctBody: 'When i = 5 the condition i <= 5 is true, so it runs one more time and then i becomes 6 and the loop stops. The boundary is handled correctly. The real problem is hiding somewhere else.',
        wrongLabel: 'Check again — the edge actually works here',
        wrongBody: 'i <= 5 correctly includes 5 and stops after. Nothing breaks at the boundary. Keep looking at the other checks to find where the real issue is.',
        reactionCorrect: 'So the edges are fine. The bug has to be in how many times it actually runs.',
        reactionIncorrect: 'Oh okay, so the edge case is actually fine. The problem is somewhere else.',
        recapNote: 'The boundary condition at i = 5 runs correctly and stops cleanly. No edge case failure.',
      },
      {
        title: 'Extra Iteration Check',
        teacherLine: 'Count with me. Starting at 0 and going to 5 with i++, how many times does this loop actually run?',
        studentLine: 'Wait... it prints 0 too? I did not ask for 0! The AI got it wrong!',
        question: 'Does the loop run one extra time? Count the iterations — starting at 0 and ending at 5 with i++, how many times does the loop actually run?',
        correctIsIssue: true,
        correctLabel: 'Good instinct — there is an extra iteration',
        correctBody: 'Starting at 0 and going to 5 means the loop runs 6 times, printing 0, 1, 2, 3, 4, 5. Alex asked for 5 numbers and gets 6. This is the off-by-one error. The console output is now revealed.',
        wrongLabel: 'Check again — there is an extra iteration',
        wrongBody: 'Count again: i goes 0, 1, 2, 3, 4, 5. That is 6 iterations. The loop runs one extra time. This is the bug.',
        reactionCorrect: 'Six times! I only wanted five numbers. The AI gave me one extra the whole time.',
        reactionIncorrect: 'Oh no, 0 through 5 is actually 6 numbers. I did not think about that.',
        highlight: 'loop',
        recapNote: 'The loop runs 6 times (0 through 5), not 5. The off-by-one in the start value causes one extra unwanted iteration.',
      },
      {
        title: 'Missing Iteration Check',
        teacherLine: 'Good observation. The values 1 to 5 are all present. The issue is not missing iterations — it is the extra 0 at the start.',
        studentLine: 'So it did not stop too early. It actually started too early!',
        question: 'Now that we know it runs 6 times, does it also miss any expected values? Is every number from 1 to 5 present in the output?',
        correctIsIssue: false,
        correctLabel: 'Good instinct — nothing is missing',
        correctBody: 'The numbers 1 through 5 are all there. The problem is not that it stops too early. The problem is that it starts too early, at 0, adding an extra value at the beginning.',
        wrongLabel: 'Check again — nothing is actually missing',
        wrongBody: 'Look at the output: 0, 1, 2, 3, 4, 5. All of 1 through 5 are there. The issue is the extra 0 at the start, not a missing value at the end.',
        reactionCorrect: 'Right, 1 through 5 are all there. The loop did not stop too early, it just started in the wrong place.',
        reactionIncorrect: 'Oh, all the numbers I wanted are actually there. The problem is just that extra 0 at the beginning.',
        recapNote: 'Values 1 through 5 are all present in the output. No expected values are missing, just one extra value at the start.',
      },
      {
        title: 'Match Check',
        teacherLine: 'Last step. Does the actual output match what Alex asked for? That is the final verdict.',
        studentLine: 'I cannot believe I almost used that code! Thank you for teaching me this checklist.',
        question: 'Does the actual output match what Alex requested? He asked for 1, 2, 3, 4, 5. The loop outputs 0, 1, 2, 3, 4, 5. Do they match?',
        correctIsIssue: true,
        correctLabel: 'Good instinct — the output does not match',
        correctBody: 'The output is 0, 1, 2, 3, 4, 5. Alex asked for 1, 2, 3, 4, 5. They do not match. The fix is simple: change i = 0 to i = 1. That is it.',
        wrongLabel: 'Check again — the output does not match',
        wrongBody: 'Compare carefully. Requested: 1, 2, 3, 4, 5. Actual: 0, 1, 2, 3, 4, 5. They are different. The code fails the final match test.',
        reactionCorrect: 'The outputs are totally different! I would have shown my students the wrong result if I had not run these checks.',
        reactionIncorrect: 'Oh, they really do not match. The 0 at the start makes it a completely different result.',
        highlight: 'actual',
        recapNote: 'Output is 0,1,2,3,4,5, which does not match the requested 1,2,3,4,5. The code fails the final match test.',
      },
    ],
  },
  'wrong-range': {
    lang: 'es',
    code: {
      comment: '// Alex le pidió a la IA: "Imprime los números del 1 al 5"',
      loop: 'for (let i = 0; i < 5; i++) {',
      body: '  console.log(i);',
      close: '}',
      expected: '// Resultado esperado: 1, 2, 3, 4, 5',
      actualUnknown: '// Resultado real: ???',
      actualRevealed: '// Resultado real: 0, 1, 2, 3, 4',
    },
    consoleOutput: ['0', '1', '2', '3', '4'],
    consoleWarning: '// ⚠ El número 5 nunca se imprime',
    revealAt: 3,
    bugMessage: '🐛 El error principal del loop: la IA empezó en i = 0 en lugar de i = 1, y la condición i < 5 excluye el 5. La corrección: for (let i = 1; i <= 5; i++)',
    perfectMessage: '🎉 ¡Puntuación perfecta! Identificaste todos los problemas. El error principal: la IA empezó en i = 0 en lugar de i = 1.',
    checks: [
      {
        title: 'Prueba del Primer Valor',
        teacherLine: '¿El loop comienza donde se espera? El loop de Alex empieza en i = 0, pero Alex quería imprimir desde el 1.',
        question: '¿El loop comienza en el valor correcto (1)?',
        correctIsIssue: true,
        correctLabel: 'Respondiste correctamente',
        correctBody: '¡Exacto! El loop empieza en i = 0, pero debería comenzar en i = 1. Ese primer valor incorrecto es la raíz del problema.',
        wrongLabel: 'Respuesta incorrecta',
        wrongBody: '¡Revisa otra vez! El loop empieza en i = 0, ¡no en 1! Eso significa que el primer número impreso será 0, no 1.',
        hint: "Pregúntale a la IA: '¿Cuál es el valor de i en la primera iteración del loop?' Esa sola pregunta te revela el error.",
        highlight: 'loop',
      },
      {
        title: 'Prueba del Último Valor',
        teacherLine: '¿El loop se detiene en el valor final correcto? La condición es i < 5, así que el último valor de i es 4.',
        question: '¿El loop termina en el valor correcto (5)?',
        correctIsIssue: true,
        correctLabel: 'Respondiste correctamente',
        correctBody: '¡Correcto! La condición i < 5 hace que el loop se detenga antes de imprimir 5. El loop imprime 0, 1, 2, 3, 4 — ¡nunca llega al 5!',
        wrongLabel: 'Respuesta incorrecta',
        wrongBody: '¡Vuelve a verificar! Con i < 5, el loop se detiene cuando i llega a 5 — pero nunca imprime 5. El último valor impreso es 4.',
        hint: 'Agrego un console.log al final... y veo que el último número es 4. ¡Eso está mal! Se suponía que imprimiera hasta el 5.',
        highlight: 'loop',
      },
      {
        title: 'Prueba de Borde',
        teacherLine: '¿Qué sucede en los límites del loop? Con i = 0 como inicio y i < 5 como condición, ¿cuántas iteraciones ocurren en total?',
        question: '¿El loop ejecuta exactamente 5 iteraciones (sin más ni menos)?',
        correctIsIssue: true,
        correctLabel: 'Respondiste correctamente',
        correctBody: '¡Muy bien! Aunque el loop ejecuta exactamente 5 iteraciones, los valores están desplazados: 0, 1, 2, 3, 4 en lugar de 1, 2, 3, 4, 5. ¡El número de repeticiones está bien, pero el rango no!',
        wrongLabel: 'Respuesta incorrecta',
        wrongBody: '¡Cuidado! El loop ejecuta 5 iteraciones (i = 0, 1, 2, 3, 4), pero los 5 valores son 0–4, ¡no 1–5! El conteo es correcto, pero los valores están desplazados.',
        hint: "Hay una diferencia entre 'número de iteraciones' y 'valores impresos'. Este loop itera 5 veces — ¡pero imprime los números incorrectos!",
      },
      {
        title: 'Verificación de Iteración Extra',
        teacherLine: '¿El loop corre una vez de más accidentalmente? Con i = 0 y i < 5, obtenemos i = 0, 1, 2, 3, 4 — eso son 5 valores, pero incluye el 0.',
        question: '¿El loop corre exactamente la cantidad correcta de veces sin iteraciones extra?',
        correctIsIssue: true,
        correctLabel: 'Respondiste correctamente',
        correctBody: '¡Perfecto! El 0 es una iteración extra no deseada. Iniciando en i = 0 se obtiene un número más de lo que Alex quería — el código de la IA tiene un error clásico de uno de más.',
        wrongLabel: 'Respuesta incorrecta',
        wrongBody: '¡Espera! El loop imprime 0, 1, 2, 3, 4 — eso son 5 números, pero se pidió imprimir del 1 al 5. El 0 es una iteración extra que no debería estar.',
        hint: "Entonces, ¿la IA me dio un error de 'uno de más'? Si empezara en i = 1, ¡obtendría exactamente 1, 2, 3, 4, 5!",
        highlight: 'loop',
      },
      {
        title: 'Verificación de Iteración Faltante',
        teacherLine: '¿El loop se detiene demasiado pronto? La condición es i < 5, así que el 5 nunca se imprime. Alex quería imprimir del 1 al 5 — el 5 es el valor faltante.',
        question: '¿El loop imprime todos los valores requeridos (1 al 5 inclusive)?',
        correctIsIssue: true,
        correctLabel: 'Respondiste correctamente',
        correctBody: '¡Exacto! El número 5 nunca se imprime porque la condición i < 5 lo excluye. Para incluirlo, necesitaríamos i <= 5.',
        wrongLabel: 'Respuesta incorrecta',
        wrongBody: '¡Revisa la consola! El 5 nunca aparece en la salida. Con i < 5, el loop se detiene cuando i = 4. El 5 es la iteración faltante.',
        hint: 'Siempre revisa si el último valor requerido aparece en la salida. Aquí, el 5 estará ausente — ese es el valor faltante.',
      },
      {
        title: 'Verificación de Coincidencia',
        teacherLine: '¿La salida real coincide con lo que se solicitó? Alex le pidió a la IA que imprimiera los números del 1 al 5. La salida real es: 0, 1, 2, 3, 4.',
        question: '¿La salida coincide exactamente con el comportamiento solicitado?',
        correctIsIssue: true,
        correctLabel: 'Respondiste correctamente',
        correctBody: '¡Perfecto! La salida real (0, 1, 2, 3, 4) no coincide con lo que se pidió (1, 2, 3, 4, 5). Es momento de pedirle a la IA que lo corrija: cambiar i = 0 a i = 1 y i < 5 a i <= 5.',
        wrongLabel: 'Respuesta incorrecta',
        wrongBody: '¡Mira más de cerca! Alex pidió 1, 2, 3, 4, 5 — pero la IA generó código que imprime 0, 1, 2, 3, 4. ¡No coincide en absoluto!',
        hint: "Así que la IA no entendió bien el prompt, ¿verdad? Probablemente deba dar instrucciones más claras la próxima vez, como 'comienza en 1 e incluye el 5'.",
        highlight: 'actual',
      },
    ],
  },
};
